### ISSUE TITLE
CSS imported twice when changing colors

### ISSUE THREAD

**Issue by jandillmann** [mike-north/ember-material-lite#43]
When I import the color definitions into my `app.scss`, change the primary and accent color, and import the `material-design-lite` styles after that (like described in the `README.md`) I end up having two nearly exact copies of all styles available in my Ember.js app. First, the original ones in `vendor.css`, and second the ones with changed colors in `app.css`. Is it possible to have the material-design-lite styles with changed colors in the `vendor.css` file only?

**Comment by mike-north** [comment]
I'm sure that there's a more reasonable solution. I'll look into it this week

**Comment by hdra** [comment]
Hi,
I don't think the issue only occurs when a variable is changed, the style declarations will always be duplicated, one in the `app.css` from the SASS `include` statement, and another one concatenated into `vendor.css`.

May I suggest removing this line from the `index.js`?

```
app.import(app.bowerDirectory + '/material-design-lite/material.css', { destDir: 'material-design-lite/css' });
```

Since the stylesheets is going to be included in the app styles anyway (by the `@import 'material-design-lite';` in the `app.scss`, there is no reason to put the inside the `vendor.css`. This also have the added benefit of being able to pick and choose which material components to include.

If you're alright with this approach, I'll prepare a PR to fix this. (I currently had to use a fork with these changes applied to get around this issue: https://github.com/hdra/ember-material-lite)

**Comment by mike-north** [comment]
@hdra yep, that's a good solution. Please prepare the PR :)

**Comment by mike-north** [comment]
Also make sure you manually test scenarios with and [without sass](https://github.com/mike-north/ember-material-lite#without-sass)

**Comment by hdra** [comment]
I am a little bit confused on the non-sass part.

Does this actually work though?
```
@import "bower_components/material-design-lite/material.css";
```

I think that file is not copied to the assets diretory by default, and the current concatenation into `vendor.css` would automatically include the styles, so there is no need to include the styles in the css file.

I'll just send a separate PR to update the instruction on how to use it without SASS.
